//https://www.jenkins.io/doc/book/pipeline/shared-libraries/
//https://www.tutorialworks.com/jenkins-shared-library/
@Library('pipeline-library') _


pipeline {
    agent any

    stages {
        stage('Build Instance') {
            steps {
                script {
                    echo "WEB_SERVER_NAME: ${params.WEB_SERVER_NAME}"
                    // echo "envHome = ${env.HOME}"
                    // sh "mkdir ${env.HOME}/${params.WEB_SERVER_NAME}"
                    // sh "cp -R terraform/aws ${env.HOME}/${params.WEB_SERVER_NAME}"
                    // def data = callTerraform('apply',"${env.HOME}/${params.WEB_SERVER_NAME}/aws","${params.WEB_SERVER_NAME}")
                    // echo "${data['ip_address']}"
                }
            }
        }
        stage('Deploy') {
            steps {
                script {
                    echo 'Deploying....'
                }
            }
        }
    }
}