pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building..'
            }
        }
        stage('Test') {
            steps {
                script {
                    if (params.HOURS == "11"){
                        echo "oded viner"
                    }
                    if (params.HOURS == "12"){
                        echo "oren viner"
                    }
         
                }
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}
