//https://www.jenkins.io/doc/book/pipeline/shared-libraries/
//https://www.tutorialworks.com/jenkins-shared-library/
@Library('pipeline-library') _


pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building..'
            }
        }
        stage('Test') {
            steps {
                script {
                    echo "HOURS123: ${params.HOURS}"
                    callLoop(15)
                    // jobResult = build job: 'job2',
                    //     propagate: false,
                    //     parameters: [
                    //         string(name: 'HOURS', value: String.valueOf("${params.HOURS}")),
                    //     ]
         
                }
                // echo "jobResult: ${jobResult.result}"
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}
