//https://www.jenkins.io/doc/book/pipeline/shared-libraries/
//https://www.tutorialworks.com/jenkins-shared-library/
@Library('pipeline-library') _


pipeline {
    agent any

    stages {
        stage('Destroy Instance') {
            steps {
                script {

                    sh "rm -rf ${env.HOME}/${params.WEB_SERVER_NAME}"
                }
            }
        }
    }
}